.TH "signal.cpp" 3 "Wed Sep 27 2017" "Version 1.0" "Lab 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
signal.cpp \- 
.SH SYNOPSIS
.br
.PP
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
.nf
20               {
21   std::thread threadOne, threadTwo;
22   std::shared_ptr<Semaphore> sem( new Semaphore);
24   threadOne=std::thread(taskTwo,sem);
25   threadTwo=std::thread(taskOne,sem);
26   std::cout << "Launched from the main\n";
27   threadOne\&.join();
28   threadTwo\&.join();
29   return 0;
30 }
.fi
.SS "void taskOne (std::shared_ptr<\fBSemaphore\fP> theSemaphore)"

.PP
.nf
5                                                    {
6   std::cout <<"I ";
7   std::cout << "must ";
8   std::cout << "print ";
9   std::cout << "first"<<std::endl;
10   theSemaphore->Signal();
11 }
.fi
.SS "void taskTwo (std::shared_ptr<\fBSemaphore\fP> theSemaphore)"

.PP
.nf
12                                                    {
13   theSemaphore->Wait();
14   std::cout <<"This ";
15   std::cout << "will ";
16   std::cout << "appear ";
17   std::cout << "second"<<std::endl;
18 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 1 from the source code\&.
